// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackingSystem.Data;

namespace TrackingSystem.Data.Migrations
{
    [DbContext(typeof(AssetsContext))]
    [Migration("20200502224748_CreateAssestsIT")]
    partial class CreateAssestsIT
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrackingSystem.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("Asset");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetTypeId = 2,
                            Description = "37.5\" Class 21:9 UltraGear™ Nano IPS 1ms Curved Gaming Monitor w / G - Sync®",
                            Manufacturer = "LG",
                            Model = "38GL950G-B",
                            SerialNumber = "N1000401",
                            TagNumber = "1002001"
                        },
                        new
                        {
                            Id = 2,
                            AssetTypeId = 2,
                            Description = "34\" 21:9 UltraWide® WQHD Nano IPS Monitor with Thunderbolt™ 3",
                            Manufacturer = "LG",
                            Model = "34WL850-W",
                            SerialNumber = "N1000402",
                            TagNumber = "1002002"
                        },
                        new
                        {
                            Id = 3,
                            AssetTypeId = 1,
                            Description = "Intel® Core™ i7-9700T (2 GHz base frequency, up to 4.3 GHz with Intel® Turbo Boost Technology, 12 MB cache, 8 cores)",
                            Manufacturer = "HP",
                            Model = "33BC850-W",
                            SerialNumber = "D1000402",
                            TagNumber = "1001001"
                        },
                        new
                        {
                            Id = 4,
                            AssetTypeId = 3,
                            Description = "The Cisco IP Phone 8800 Series is a great fit for businesses of all sizes seeking secure, high-quality, full-featured VoIP.",
                            Manufacturer = "Cisco",
                            Model = "IPPhone-8800",
                            SerialNumber = "C1000402",
                            TagNumber = "1003001"
                        });
                });

            modelBuilder.Entity("TrackingSystem.Domain.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssetType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Desktop Computer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Computer Monitor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phone"
                        });
                });

            modelBuilder.Entity("TrackingSystem.Domain.Asset", b =>
                {
                    b.HasOne("TrackingSystem.Domain.AssetType", "AssetTypeNavProperty")
                        .WithMany("AssetsNavProperty")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
